name: aad_oauth
description: A Flutter OAuth package for performing user authentication against
  Azure Active Directory OAuth2 v2.0 endpoint.
version: 1.0.0
homepage: https://github.com/Earlybyte/aad_oauth

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.7.0
  js: ^0.7.1
  http: ^1.1.0
  shared_preferences: ^2.2.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  auto_route: ^7.8.3

  # flutter_secure_storage: ^9.0.0
  flutter_secure_storage:
    git:
      # url: https://github.com/ThexXTURBOXx/flutter_secure_storage.git
      url: https://github.com/fegea-immo/flutter_secure_storage.git
      ref: develop
      path: flutter_secure_storage

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/msalv2.js
