name: aad_oauth
description: A Flutter OAuth package for performing user authentication against
  Azure Active Directory OAuth2 v2.0 endpoint.
version: 0.4.1
homepage: https://github.com/Earlybyte/aad_oauth

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  http: ^0.13.3
  pedantic: ^1.11.1
  webview_flutter: ^2.4.0
  shared_preferences: ^2.0.9
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
